/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

import ifsc.poo.nave.modelos.NaveEspacial;
import ifsc.poo.nave.modelos.NaveExploradora;

public class App {

    public static void main(String[] args) {
        NaveEspacial n = new NaveExploradora();
        System.out.println(n.getVelocidadeMaxima());
    }
}
